// ====================================================================
// PYTANIA KONKURSOWE - STOP CYBERPRZEMOCY
// Edycja pytań tylko w tym pliku
// ====================================================================

const PYTANIA = [
  { nr:1, t:"Czym JEST cyberprzemoc?",
    a:["Granie online z kolegami przez wiele godzin",
       "Krzywdzenie kogoś przy użyciu telefonu, internetu lub mediów społecznościowych",
       "Kupowanie skinów w grze za prawdziwe pieniądze",
       "Każda kłótnia z rodzeństwem na czacie rodzinnym"], k:1 },
  { nr:2, t:"Które z poniższych zachowań NIE jest cyberprzemocą?",
    a:["Wysyłanie obraźliwych wiadomości na czacie",
       "Wstawienie ośmieszającego zdjęcia kolegi bez jego zgody",
       "Założenie fałszywego konta podszywającego się pod koleżankę",
       "Kulturalne zwrócenie komuś uwagi w komentarzu, że popełnił błąd ortograficzny"], k:3 },
  { nr:3, t:"Hejt to:",
    a:["Modny taniec z TikToka",
       "Nienawistne, obraźliwe komentarze pisane w internecie",
       "Nazwa nowej gry online",
       "Specjalny filtr na Snapchacie"], k:1 },
  { nr:4, t:"Co to jest „flaming”?",
    a:["Wysyłanie zdjęć ognia w wiadomościach",
       "Kłótnia w internecie z używaniem ostrych, obraźliwych słów",
       "Specjalny efekt w grach komputerowych",
       "Rodzaj smartfona"], k:1 },
  { nr:5, t:"Podszywanie się pod kogoś w internecie (np. założenie fałszywego konta z czyimś zdjęciem) to:",
    a:["Niewinny żart, za który nic nie grozi",
       "Tzw. impersonating — jedna z form cyberprzemocy",
       "Sposób na zdobycie nowych znajomych",
       "Coś, co robią tylko hakerzy w filmach"], k:1 },
  { nr:6, t:"Dostajesz na czacie obraźliwą wiadomość od nieznajomej osoby. Co powinieneś zrobić NAJPIERW?",
    a:["Odpisać tej osobie tak samo brzydko, żeby się odegrać",
       "Nie odpowiadać, zrobić zrzut ekranu i pokazać dorosłemu, któremu ufasz",
       "Skasować wiadomość i nikomu nie mówić",
       "Wysłać tę wiadomość dalej do wszystkich znajomych, żeby ich ostrzec"], k:1 },
  { nr:7, t:"Twój kolega jest ofiarą cyberprzemocy. Najlepiej:",
    a:["Udawać, że nic się nie dzieje, bo to nie twoja sprawa",
       "Też się z niego śmiać, żeby nie być następną ofiarą",
       "Wesprzeć go i razem z nim powiedzieć o tym dorosłemu",
       "Samodzielnie zaatakować sprawcę w internecie"], k:2 },
  { nr:8, t:"Pod jakim numerem działa Telefon Zaufania dla Dzieci i Młodzieży?",
    a:["112","997","116 111","800 100 100"], k:2 },
  { nr:9, t:"PUŁAPKA: Ktoś w internecie pisze do Ciebie: „Jeśli powiesz rodzicom, będzie jeszcze gorzej. To nasza tajemnica”. Co robisz?",
    a:["Słucham, bo obietnica to obietnica",
       "Natychmiast mówię o tym rodzicom lub innemu zaufanemu dorosłemu — to klasyczna metoda zastraszania",
       "Mówię tylko najlepszemu koledze i nikomu więcej",
       "Zmieniam hasło i sprawa załatwiona"], k:1 },
  { nr:10, t:"Dlaczego warto robić zrzuty ekranu (screeny) obraźliwych wiadomości?",
    a:["Żeby pochwalić się znajomym",
       "Żeby mieć dowód, który można pokazać rodzicom, nauczycielowi lub policji",
       "Żeby wstawić je na swoje konto na TikToku",
       "Nie warto, bo zajmują miejsce w telefonie"], k:1 },
  { nr:11, t:"Które hasło jest NAJBEZPIECZNIEJSZE?",
    a:["123456","moje_imie2014","Z!ml4Pies#7uK","haslo"], k:2 },
  { nr:12, t:"Komu MOŻNA podać swoje hasło do konta?",
    a:["Najlepszemu przyjacielowi, bo mu ufasz",
       "Osobie, która napisała na czacie, że jest pracownikiem gry",
       "Rodzicom lub opiekunom",
       "Każdemu, kto ładnie poprosi"], k:2 },
  { nr:13, t:"PUŁAPKA: W grze online ktoś wysyła Ci link i pisze: „Kliknij, dostaniesz darmowe V-bucki / Robuxy / skiny”. Co robisz?",
    a:["Klikam, bo to fajna okazja",
       "Klikam, ale tylko jeden raz",
       "Nie klikam — to typowy oszust (scam), który chce ukraść konto lub dane",
       "Wysyłam link dalej do znajomych, żeby też dostali"], k:2 },
  { nr:14, t:"Czego NIE wolno udostępniać obcym osobom w internecie?",
    a:["Imienia swojego kota",
       "Adresu domu, numeru telefonu, nazwy szkoły, zdjęć z domu",
       "Tytułu ulubionej książki",
       "Imienia ulubionego YouTubera"], k:1 },
  { nr:15, t:"Co oznacza skrót RODO w kontekście Twoich danych?",
    a:["Rodzinny Odpoczynek Domowy Online",
       "Rozporządzenie o Ochronie Danych Osobowych — chroni Twoje dane",
       "Rada Obrony Dzieci Online",
       "Rodzaj nowej aplikacji do gier"], k:1 },
  { nr:16, t:"Najmłodszy wiek, w którym ZGODNIE Z REGULAMINEM można założyć konto na TikToku, Instagramie, Snapchacie czy Facebooku, to:",
    a:["7 lat","10 lat","13 lat","Nie ma żadnego ograniczenia"], k:2 },
  { nr:17, t:"PUŁAPKA: Kolega prosi Cię, żebyś wysłał mu śmieszne zdjęcie innego kolegi z klasy, które razem zrobiliście. Jak postępujesz?",
    a:["Wysyłam, bo to tylko żart między kumplami",
       "Wysyłam, ale proszę, żeby nie pokazywał innym",
       "Nie wysyłam — bez zgody osoby ze zdjęcia nie wolno go nikomu udostępniać",
       "Wysyłam i jeszcze dodaję śmieszny komentarz"], k:2 },
  { nr:18, t:"Nieznajomy w grze online pisze, że ma 11 lat, lubi te same gry i chce się spotkać „na placu zabaw”. Co robisz?",
    a:["Idę, ale biorę kolegę",
       "Umawiam się, ale w innym miejscu",
       "Nie idę i mówię o tym rodzicom — osoba w internecie może kłamać o swoim wieku",
       "Idę sam, żeby sprawdzić"], k:2 },
  { nr:19, t:"Co to jest „sexting” i dlaczego dzieci nigdy nie powinny w tym uczestniczyć?",
    a:["Granie w gry erotyczne — jest dozwolone od 10 lat",
       "Wysyłanie nagich lub roznegliżowanych zdjęć — w przypadku dzieci jest to nielegalne i bardzo niebezpieczne",
       "Pisanie SMS-ów — jest całkiem bezpieczne",
       "Robienie selfie — nie ma w tym nic złego"], k:1 },
  { nr:20, t:"PUŁAPKA: Klasa założyła grupę na komunikatorze i wszyscy zaczęli wyśmiewać jedną koleżankę. Ty:",
    a:["Też dopisujesz coś śmiesznego, żeby pasować do grupy",
       "Tylko się śmiejesz emotkami — przecież nic nie napisałeś",
       "Nie reagujesz, ale i tak czytasz",
       "Sprzeciwiasz się, opuszczasz grupę i mówisz o tym wychowawcy lub rodzicom — milczenie też jest formą zgody na hejt"], k:3 },
  { nr:21, t:"Cyberprzemoc różni się od zwykłej przemocy w szkole tym, że:",
    a:["Jest mniej groźna, bo dzieje się tylko w internecie",
       "Może docierać do ofiary 24 godziny na dobę i bardzo szybko rozprzestrzenia się wśród wielu osób",
       "Zawsze jest anonimowa i nie da się złapać sprawcy",
       "Jest legalna, bo przepisy prawa nie obejmują internetu"], k:1 },
  { nr:22, t:"Czy sprawca cyberprzemocy może ponieść konsekwencje prawne, nawet jeśli ma 10 lat?",
    a:["Nie, dzieciom nigdy nic nie grozi",
       "Tak — sprawą może zająć się sąd rodzinny, a odpowiedzialność za szkody mogą ponieść również rodzice",
       "Tylko jeśli zostanie złapany na gorącym uczynku przez policję",
       "Nie, w internecie wszystko jest anonimowe i bezkarne"], k:1 },
  { nr:23, t:"Co to jest „deepfake”?",
    a:["Bardzo głęboki sen",
       "Spreparowane przez sztuczną inteligencję nagranie lub zdjęcie, na którym ktoś robi lub mówi coś, czego naprawdę nie zrobił",
       "Specjalny tryb ciemny w aplikacjach",
       "Nowy filtr na Instagramie do zabawy"], k:1 },
  { nr:24, t:"Sztuczna inteligencja (AI), taka jak ChatGPT czy Gemini:",
    a:["Zawsze mówi prawdę i nigdy się nie myli",
       "Może się mylić i podawać nieprawdziwe informacje, dlatego trzeba je sprawdzać",
       "Jest żywą osobą, która siedzi po drugiej stronie ekranu",
       "Czyta Twoje myśli"], k:1 },
  { nr:25, t:"PUŁAPKA: Dostajesz wiadomość głosową, która brzmi jak głos Twojego taty: „Synku, podaj kod z SMS-a, który zaraz przyjdzie”. Co robisz?",
    a:["Podaję kod, bo to przecież tata",
       "Najpierw oddzwaniam do taty na jego znany numer i pytam, czy to naprawdę on — głosy można dziś podrobić przez AI",
       "Wysyłam mu kod, ale dodaję „cześć tato”",
       "Wysyłam kod tylko jeśli głos brzmi podobnie"], k:1 },
  { nr:26, t:"Co to jest phishing?",
    a:["Łowienie ryb przez internet",
       "Oszustwo, w którym ktoś podszywa się np. pod bank lub sklep, by wyłudzić hasło lub dane",
       "Aplikacja do zamawiania jedzenia",
       "Rodzaj gry komputerowej"], k:1 },
  { nr:27, t:"Twój przyjaciel pisze do Ciebie z konta swojej mamy, że zapomniał hasła i prosi, żebyś mu je podał. Co robisz?",
    a:["Podaję hasło — to przecież przyjaciel",
       "Nie podaję hasła i dzwonię do przyjaciela na jego znany numer, żeby sprawdzić, czy to naprawdę on — konto mamy mogło zostać przejęte",
       "Podaję hasło tylko po połowie",
       "Zmieniam hasło i wysyłam mu nowe"], k:1 },
  { nr:28, t:"Zasada „pomyśl, zanim klikniesz / wyślesz” oznacza, że przed napisaniem czegoś w internecie trzeba zastanowić się, czy:",
    a:["Wiadomość jest wystarczająco zabawna",
       "Jest zgodna z prawdą, czy nikogo nie skrzywdzi i czy nie powstydzimy się jej za rok",
       "Ma odpowiednią liczbę emotek",
       "Spodoba się popularnemu YouTuberowi"], k:1 },
  { nr:29, t:"Wszystko, co kiedyś wrzucisz do internetu (zdjęcie, komentarz, film):",
    a:["Można łatwo i całkowicie usunąć w każdej chwili",
       "Może zostać tam na długo — inni mogą zrobić zrzut ekranu lub skopiować, dlatego mówi się o „cyfrowym śladzie”",
       "Znika automatycznie po 24 godzinach",
       "Widzi tylko ten, kogo oznaczysz"], k:1 },
  { nr:30, t:"PUŁAPKA: Które stwierdzenie jest PRAWDZIWE?",
    a:["W internecie zawsze mogę zachować pełną anonimowość, więc mogę pisać, co chcę",
       "Ofiara cyberprzemocy zawsze jest sama sobie winna",
       "Świadek cyberprzemocy, który milczy i nie reaguje, też ma swój udział w krzywdzeniu drugiej osoby",
       "Cyberprzemoc dotyczy tylko dzieci, dorośli się tym nie zajmują"], k:2 }
];
